---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Start MySQL container
      docker_container:
        name: mysql-db
        image: mysql:8.0
        state: started
        ports:
          - "3307:3306"
        env:
          MYSQL_ROOT_PASSWORD: "Rambo@123"
          MYSQL_DATABASE: subscribersdb

    - name: Wait for MySQL to be ready
      wait_for:
        host: 127.0.0.1
        port: 3307
        delay: 20
        timeout: 60

    - name: Run Flyway migrations
      command: >
        cmd.exe /c
        "C:\\ProgramData\\chocolatey\\lib\\flyway.commandline\\tools\\flyway-10.21.0\\flyway.cmd
        -url=jdbc:mysql://localhost:3307/subscribersdb?allowPublicKeyRetrieval=true^^^&useSSL=false
        -user=root
        -password=Rambo@123
        -locations=filesystem:C:/Users/puneet/Desktop/DevOps_Sem2/Database_Automation/PROG8850Week2-3/flyway/sql
        -jarDirs=C:/ProgramData/chocolatey/lib/flyway.commandline/tools/flyway-10.21.0/drivers
        migrate"



